// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Clase13_ReverseEngineering.Models
{
    public partial class Ansewers
    {
        public int Id { get; set; }
        public int? QuestionId { get; set; }

        public virtual Questions Question { get; set; }
    }
}