// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Clase13_ReverseEngineering.Models
{
    public partial class Interviewees
    {
        public Interviewees()
        {
            Intreviews = new HashSet<Intreviews>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public virtual ICollection<Intreviews> Intreviews { get; set; }
    }
}