// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Clase13_ReverseEngineering.Models
{
    public partial class Interviewers
    {
        public Interviewers()
        {
            Interviews = new HashSet<Intreviews>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? DateOfBirth { get; set; }

        public virtual ICollection<Intreviews> Interviews { get; set; }
    }
}