// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Clase13_ReverseEngineering.Models
{
    public partial class Intreviews
    {
        public Intreviews()
        {
            Interviewers = new HashSet<Interviewers>();
            Questions = new HashSet<Questions>();
        }

        public int Id { get; set; }
        public int IntervieweeId { get; set; }
        public DateTime? Date { get; set; }
        public decimal? Score { get; set; }

        public virtual Interviewees Interviewee { get; set; }

        public virtual ICollection<Interviewers> Interviewers { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
    }
}